[package]
name = "bongusbingis/loader"
description = "Fork of loader to allow synchronous .SpawnAll() for init functions"
version = "2.0.1"
license = "MIT"
authors = ["Stephen Leitnick"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
