name: Deploy to Staging

on:
  push:
    branches:
    - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: ok-nick/setup-aftman@v0.4.2
      name: Install aftman
      with:
          token: ${{ SECRETS.GITHUB_TOKEN }}

    - name: Lint
      run: |
        selene ./src
  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment: CI/CD
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: ok-nick/setup-aftman@v0.3.0
      name: Install aftman
      env: 
        API_KEY: ${{ secrets.API_KEY }}
      with:
        token: ${{ SECRETS.GITHUB_TOKEN }}

    - name: "Deploy"
      run: |
        rbxcloud experience publish --filename game.rbxl --place-id ${{ vars.STAGING_PLACE_ID }} --universe-id ${{ vars.UNIVERSE_ID }} -t published --api-key ${{ secrets.API_KEY }}