name: Deploy to Staging

on:
  push:
    branches:
    - master

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: CI/CD
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: ok-nick/setup-aftman@v0.3.0
      name: Install aftman
      with:
          token: ${{ SECRETS.GITHUB_TOKEN }}

    - run: rbxcloud experience publish --filename game.rbxl --place-id ${{ vars.STAGING_PLACE_ID }} --universe-id ${{ vars.UNIVERSE_ID }} -t published --api-key ${{ secrets.API_KEY }}